### ISSUE TITLE
How to display/debug multiple data layers

### ISSUE THREAD

**Issue by dns2utf8-novaziun** [felix-mu/geomap-wms-panel#32]
Hi there

Thank you for the fork.
I have 4 data layers displaying seperate geojson paths.
Currently I have them in 4 queries that return distinct paths and 4 layers that should show them with seperate colors.

Sadly, I can only see the last layer. The legend enabling them showed me that the layers all use the same query instead of their seperate one.
Do you have any pointers on how to seperate them?

Best, Stefan

**Comment by felix-mu** [comment]
Hi Stefan, thank you for reaching out. 
Could you provide some resources and steps to follow so that I could reproduce the issue in my local environment?
Also which version of the plugin are you using?

Best regards, Felix

**Comment by dns2utf8-novaziun** [comment]
Hi Felix

Certainly :) I use v1.0.1 installed on a self-hosted k3s container running the image `grafana/grafana:11.1.0`
Each query has SQL like this:
```sql
SELECT time_bucket('5 minutes', "timestamp") AS "time", 
  ST_AsGeoJSON(ST_MakeLine(pos ORDER BY timestamp)) AS "geojson"
FROM position
WHERE $__timeFilter(timestamp) AND machine_id = 41
GROUP BY time
ORDER BY time
;
```

Then I added the layers like this:
![grafik](https://github.com/user-attachments/assets/12bce107-001d-4da2-b1a2-bac253c543f7)

Sadly I can only see one track. When I change the visibilty in the layers the color changes because the corresponding layer is on top now.
But they use the same data for some reason.

Thank you in advance, Stefan

**Comment by dns2utf8-novaziun** [comment]
Also, I noticed that I can switch the used query with a `Filter data by query refId` transformation, but it switched all the layers.
Do I need to add a label to seperate the layers?

**Comment by felix-mu** [comment]
At the first glance I cannot see where the reason for this issue  lays. Have you already tried to explicitely choose GeoJSON in the location configuration?

**Comment by dns2utf8-novaziun** [comment]
Yes, I did set the Layer -> Location to Geojson and even tried to tell it the fields explicitly, but no change.
So, the auto detection works :) 

The queries are labeled as "MachineXY" and are all different.

Is it possible that they somehow share the `refid` in the background? Maybe that is the bug in Grafana itself?

Also I noticed that my query result has this form:
```
time  | geojson
00:01 | 01841098...
00:02 | 01841098...
00:03 | 01841098...
```

Since I want to display multiple tracks on the same graph, I don't mind if they are on the same layer.

Would I need to have a structure like this?
```
time  | geojson_01  | geojson_02  | geojson03   | ...
00:01 | 01841098... | 01841098... | NULL        | ...
00:02 | 01841098... | 01841098... | NULL        | ...
00:03 | 01841098... | NULL        | 01841098... | ...
```

Or would this be okay?
```
time  | geojson     | machine   |
00:01 | 01841098... | machine01 |
00:01 | 01841098... | machine02 |
00:01 | 01841098... | machine03 |
```

**Comment by felix-mu** [comment]
Could you send me some sample data? I honestly never experienced the phenomenon that you describe...

To show the data in one layer I would recommend the second option that you brought up.

**Comment by dns2utf8-novaziun** [comment]
Yes, I have a TimescaleDB, but I use the integrated PostgreSQL adapter with the timescale flag enabled.

Let me try to get some data that I am allowed to share

**Comment by felix-mu** [comment]
One more suggestion: Did you try to name the fields of geometry differently for each query, e.g. geometryA for Query A, geometryB for Query B, etc.? Might be the case that the plugin cannot handle fields with the same geometry name, but from different queries...

**Comment by felix-mu** [comment]
> One more suggestion: Did you try to name the fields of geometry differently for each query, e.g. geometryA for Query A, geometryB for Query B, etc.? Might be the case that the plugin cannot handle fields with the same geometry name, but from different queries...

Just tried it out on my local grafana, but it also works with the same name for geometry fields...
At the moment I am rather clueless tbh...

**Comment by felix-mu** [comment]
To really reproduce your issue I may ask for a Dashboard-JSON as well as some sample data, since as for now it is not possible for me to trace down the reasons for this unexpected behavior.

**Comment by felix-mu** [comment]
> One more suggestion: Did you try to name the fields of geometry differently for each query, e.g. geometryA for Query A, geometryB for Query B, etc.? Might be the case that the plugin cannot handle fields with the same geometry name, but from different queries...

I experienced the same issue you like you when using the PostgreSQL datasource. By giving each geometry field of each query an unique name across all queries I managed to display all data layer with their respective data.

**Comment by felix-mu** [comment]
Apparently you found a bug in the plugin. I already was able to locate the bug in the source code and I am going to fix it asap. With the new release of the plugin it will fixed.
In the meantime I recommend the workaround as I described above.
