### ISSUE TITLE
Difficulty displaying large numbers of points in a layer

### ISSUE THREAD

**Issue by johnhtodd** [felix-mu/geomap-wms-panel#37]
I am not able to draw a map with more than a tiny handful of points as markers.

I have a RIPE Atlas data set that I have imported into Prometheus.  The value is latency, though that is not particularly important. I have transformed the "probe_lat" and "probe_lon" values into numbers.  This is what a sample set looks like:

```
.
.
.
{probe_id="1000177", probe_lat="52.1505", probe_lon="-0.6995"} 1.44
{probe_id="1000222", probe_lat="51.5285", probe_lon="-0.7315"} 8.93
{probe_id="1000390", probe_lat="53.3475", probe_lon="-2.1285"} 34.11
.
.
.
```

If I reduce the number of results to just three by specifying the probe_ids, then the map draws and the markers appear in the correct positions.  However, if I open it up and try to draw all 403 points, the map freezes and nothing shows up on the screen.  Behaviors are very strange - after making larger requests (100 points draws after several minutes) the browser becomes unresponsive even in the "Edit" window with no data actively being pulled from the database.  This behavior is identical in Firefox and Chrome.  What am I doing wrong here?

It is not a difficult map to draw, but performance is completely unusable with anything other than a tiny number of points.  I have the same maps drawing in the "Geomap" plugin, and the same data (400+ points) draws in about 5 seconds and browser latency is entirely acceptable.  I have drawn up to 6000 at a time, though that is slower.

Suggestions are welcome - is this a bug, or an implementation problem on my side?  I have simplified the map down to what I think are the most basic functions and it still cannot draw more than 100 points without crashing my browser.

**Comment by johnhtodd** [comment]
Update: this crushes Firefox, Chrome, and Safari.  It also causes Firefox to go into a non-recoverable state in many instances, requiring force quit.

**Comment by felix-mu** [comment]
Hi, thank you for your comment.
I just tested the geomap plugin v2.0.0 with some sample data (1000 points) using the test data source and I could not reproduce the behaviour that you describe...
![grafik](https://github.com/user-attachments/assets/d6e14e42-4478-47ed-b44b-755fc4ccf7ba)
Could you please provide more information about the plugin version, plugin configuration, as well as which grafana version you are using?

**Comment by johnhtodd** [comment]
Grafana 10.2.2, the plugin is 1.0.1 (installed yesterday)  and I've attached the various screenshots of the configuration and query.  I even tried with a different computer - same results (fails on more than a small handful of points.)

![Screen Shot 2024-10-21 at 10 56 19 AM](https://github.com/user-attachments/assets/49c956d7-5623-4c06-865c-14eb1db89338)
![Screen Shot 2024-10-21 at 10 56 12 AM](https://github.com/user-attachments/assets/3e008177-9ea4-45ab-a965-73188fb73f30)
![Screen Shot 2024-10-21 at 10 58 39 AM](https://github.com/user-attachments/assets/13cf3ac2-fd19-424b-b67b-6f4d2e9a709f)

![Screen Shot 2024-10-21 at 10 58 50 AM](https://github.com/user-attachments/assets/91dd445e-57f4-4506-824e-9e4b1e45c69a)
![Screen Shot 2024-10-21 at 10 59 04 AM](https://github.com/user-attachments/assets/962ed4b5-21ff-4773-b233-5fab2e3bf49f)
![Screen Shot 2024-10-21 at 10 59 15 AM](https://github.com/user-attachments/assets/f7360605-9867-4610-bb85-5000dc76b9a8)
![Screen Shot 2024-10-21 at 10 59 21 AM](https://github.com/user-attachments/assets/f7edda56-fe5d-47fa-b029-b8c003ec6608)

**Comment by felix-mu** [comment]
Thank you for the additional information.
I just tried the plugin version 1.0.1 with grafana version 10.2.2 with sample data of 7000 point locations from my local postgresql/postgis database. Even if the responsiveness was quite laggy it still was far away from crashing the browser...
![geomap_data_links](https://github.com/user-attachments/assets/4ff955aa-9117-4e36-8af8-3a8a28ec9b5a)

**Comment by johnhtodd** [comment]
I see my problem (after setting up a test server and running through a lot of other work!):  I was not matching my "min step" with the duration of the sample set, and there were many hidden rows in the return which was overloading each point in the map.  Apologies - this can be closed.

**Comment by felix-mu** [comment]
Alright, I am glad you could resolve the issue anyways 👍
